function latex = savelatexTable(latex, filename, ex)
% An easy to save a LateX Table generated by latextable
%   
% Inputs:
%   latex       : Latex code generated by latexTable function
%   filename    : Filename to be saved to, without extension
%   ex          : Excersice number, integer from 1 to 5, giving the folder to
%                 save to
%
% Outputs:
%   path        : a string giving the path to where the file was saved

foldername = "../tables";
if ~exist(foldername, 'dir')
       mkdir(foldername);
end
if nargin > 2
    foldername = sprintf("%s/ex%d/", foldername, ex);
    if ~exist(foldername, 'dir')
           mkdir(foldername);
    end
end

% Save LaTex code as file
path = foldername + filename + ".tex";
fid=fopen(path,'w');
[nrows,ncols] = size(latex);
for row = 1:nrows
    fprintf(fid,'%s\n',latex{row,:});
end
fclose(fid);
fprintf('... LaTex Table has been saved to ''%s''\n', path);
